[2025-09-10T14:18:21.553+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-10T14:18:21.731+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.consume_and_save_batch scheduled__2025-09-10T13:48:09.132122+00:00 [queued]>
[2025-09-10T14:18:21.746+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.consume_and_save_batch scheduled__2025-09-10T13:48:09.132122+00:00 [queued]>
[2025-09-10T14:18:21.755+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-09-10T14:18:21.863+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): consume_and_save_batch> on 2025-09-10 13:48:09.132122+00:00
[2025-09-10T14:18:21.889+0000] {standard_task_runner.py:57} INFO - Started process 2031 to run task
[2025-09-10T14:18:21.893+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_postgres_batch', 'consume_and_save_batch', 'scheduled__2025-09-10T13:48:09.132122+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp3atqdf2o']
[2025-09-10T14:18:21.897+0000] {standard_task_runner.py:85} INFO - Job 116: Subtask consume_and_save_batch
[2025-09-10T14:18:21.920+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-10T14:18:21.972+0000] {task_command.py:410} INFO - Running <TaskInstance: kafka_to_postgres_batch.consume_and_save_batch scheduled__2025-09-10T13:48:09.132122+00:00 [running]> on host c905ba028b15
[2025-09-10T14:18:21.993+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-10T14:18:22.105+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_postgres_batch' AIRFLOW_CTX_TASK_ID='consume_and_save_batch' AIRFLOW_CTX_EXECUTION_DATE='2025-09-10T13:48:09.132122+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-10T13:48:09.132122+00:00'
[2025-09-10T14:18:22.106+0000] {dags_utils.py:42} INFO - Starting consumer with batch_size=50, timeout=30
[2025-09-10T14:18:22.110+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.23.0.5', 9092)]>: connecting to kafka:9092 [('172.23.0.5', 9092) IPv4]
[2025-09-10T14:18:22.251+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.23.0.5', 9092)]>: Broker version identified as 2.6
[2025-09-10T14:18:22.252+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.23.0.5', 9092)]>: Connection complete.
[2025-09-10T14:18:22.254+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('user_events',)
[2025-09-10T14:18:22.269+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-09-10T14:18:22.370+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Connection complete.
[2025-09-10T14:18:22.371+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.23.0.5', 9092)]>: Closing connection. 
[2025-09-10T14:18:22.481+0000] {cluster.py:401} INFO - Coordinator for group/***_batch_consumer is ('coordinator-1', 'host.docker.internal', 9092, None)
[2025-09-10T14:18:22.482+0000] {base.py:789} INFO - Discovered coordinator coordinator-1 for group ***_batch_consumer
[2025-09-10T14:18:22.483+0000] {base.py:848} INFO - Starting new heartbeat thread
[2025-09-10T14:18:22.484+0000] {consumer.py:366} INFO - Revoking previously assigned partitions () for group ***_batch_consumer
[2025-09-10T14:18:22.484+0000] {base.py:419} INFO - Failed to join group ***_batch_consumer: NodeNotReadyError: coordinator-1
[2025-09-10T14:18:22.487+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-09-10T14:18:22.589+0000] {base.py:419} INFO - Failed to join group ***_batch_consumer: NodeNotReadyError: coordinator-1
[2025-09-10T14:18:22.590+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Connection complete.
[2025-09-10T14:18:22.691+0000] {base.py:532} INFO - (Re-)joining group ***_batch_consumer
[2025-09-10T14:18:22.720+0000] {base.py:638} INFO - Received member id kafka-python-2.2.15-13abfeda-e556-44a8-9944-628fbb664be3 for group ***_batch_consumer; will retry join-group
[2025-09-10T14:18:22.721+0000] {base.py:419} INFO - Failed to join group ***_batch_consumer: [Error 79] MemberIdRequiredError
[2025-09-10T14:18:22.721+0000] {base.py:532} INFO - (Re-)joining group ***_batch_consumer
[2025-09-10T14:18:25.774+0000] {base.py:594} INFO - Successfully joined group ***_batch_consumer <Generation 19 (member_id: kafka-python-2.2.15-13abfeda-e556-44a8-9944-628fbb664be3, protocol: range)>
[2025-09-10T14:18:25.775+0000] {base.py:597} INFO - Elected group leader -- performing partition assignments using range
[2025-09-10T14:18:25.838+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('user_events', 0)]
[2025-09-10T14:18:25.839+0000] {consumer.py:250} INFO - Setting newly assigned partitions (('user_events', 0),) for group ***_batch_consumer
[2025-09-10T14:18:25.865+0000] {dags_utils.py:70} INFO - Received message 1: {'user_id': 632, 'event_type': 'session_start', 'city': 'Sikonge', 'country': 'Tanzania', 'lat': -6.4817697704214225, 'lon': 33.05855908729927, 'cost_usd': 823.37, 'cost_eur': 702.32, 'cost_rub': 68822.58, 'weather_temp': 33.01, 'weather_desc': 'overcast clouds', 'timestamp': '2025-09-10T13:51:01.018159+00:00'}
[2025-09-10T14:18:25.866+0000] {dags_utils.py:70} INFO - Received message 2: {'user_id': 595, 'event_type': 'view_product', 'city': 'Unknown', 'country': None, 'lat': 81.93945121720625, 'lon': 53.54043942070976, 'cost_usd': 183.8, 'cost_eur': 156.78, 'cost_rub': 15363.19, 'weather_temp': 2.16, 'weather_desc': 'overcast clouds', 'timestamp': '2025-09-10T13:51:05.784149+00:00'}
[2025-09-10T14:18:25.867+0000] {dags_utils.py:70} INFO - Received message 3: {'user_id': 611, 'event_type': 'view_product', 'city': 'Shalkarskiy', 'country': 'Kazakhstan', 'lat': 46.61553320365877, 'lon': 58.46950518625226, 'cost_usd': 272.39, 'cost_eur': 232.34, 'cost_rub': 22768.12, 'weather_temp': 22.16, 'weather_desc': 'overcast clouds', 'timestamp': '2025-09-10T13:51:09.564580+00:00'}
[2025-09-10T14:18:25.867+0000] {dags_utils.py:70} INFO - Received message 4: {'user_id': 864, 'event_type': 'session_start', 'city': '395 A Hunters Point Road', 'country': 'United States', 'lat': 35.50029881941514, 'lon': -109.03209339100147, 'cost_usd': 644.27, 'cost_eur': 549.55, 'cost_rub': 53852.25, 'weather_temp': 9.43, 'weather_desc': 'clear sky', 'timestamp': '2025-09-10T13:51:11.562829+00:00'}
[2025-09-10T14:18:25.868+0000] {dags_utils.py:70} INFO - Received message 5: {'user_id': 745, 'event_type': 'session_start', 'city': 'Antarctica', 'country': 'Antarctica', 'lat': -76.97624391465001, 'lon': -3.1377775531678083, 'cost_usd': 962.69, 'cost_eur': 821.16, 'cost_rub': 80467.85, 'weather_temp': -39.32, 'weather_desc': 'broken clouds', 'timestamp': '2025-09-10T13:51:15.388362+00:00'}
[2025-09-10T14:18:25.869+0000] {dags_utils.py:70} INFO - Received message 6: {'user_id': 707, 'event_type': 'purchase', 'city': 'Antarctica', 'country': 'Antarctica', 'lat': -78.94633666803031, 'lon': 108.02053970925743, 'cost_usd': 771.12, 'cost_eur': 657.75, 'cost_rub': 64455.19, 'weather_temp': -52.75, 'weather_desc': 'overcast clouds', 'timestamp': '2025-09-10T13:51:16.666030+00:00'}
[2025-09-10T14:18:25.869+0000] {dags_utils.py:70} INFO - Received message 7: {'user_id': 370, 'event_type': 'session_start', 'city': 'Mirninskiy', 'country': 'Russia', 'lat': 61.26936338050166, 'lon': 110.9287478971525, 'cost_usd': 258.53, 'cost_eur': 220.52, 'cost_rub': 21609.61, 'weather_temp': 7.53, 'weather_desc': 'overcast clouds', 'timestamp': '2025-09-10T13:51:19.572599+00:00'}
[2025-09-10T14:18:25.870+0000] {dags_utils.py:70} INFO - Received message 8: {'user_id': 75, 'event_type': 'view_product', 'city': 'Tibesti Est', 'country': 'Chad', 'lat': 20.414464794998707, 'lon': 20.14404360026478, 'cost_usd': 58.56, 'cost_eur': 49.95, 'cost_rub': 4894.82, 'weather_temp': 35.75, 'weather_desc': 'clear sky', 'timestamp': '2025-09-10T13:51:20.942649+00:00'}
[2025-09-10T14:18:25.871+0000] {dags_utils.py:70} INFO - Received message 9: {'user_id': 291, 'event_type': 'purchase', 'city': 'Unknown', 'country': None, 'lat': 59.698052862274004, 'lon': 151.396481362205, 'cost_usd': 366.0, 'cost_eur': 312.19, 'cost_rub': 30592.64, 'weather_temp': 9.91, 'weather_desc': 'overcast clouds', 'timestamp': '2025-09-10T13:51:26.731568+00:00'}
[2025-09-10T14:18:25.871+0000] {dags_utils.py:70} INFO - Received message 10: {'user_id': 355, 'event_type': 'session_start', 'city': 'Kenai Peninsula Borough', 'country': 'United States', 'lat': 60.177568645343484, 'lon': -150.82945904939078, 'cost_usd': 645.92, 'cost_eur': 550.96, 'cost_rub': 53990.16, 'weather_temp': 11.04, 'weather_desc': 'light rain', 'timestamp': '2025-09-10T13:51:28.280255+00:00'}
[2025-09-10T14:18:55.883+0000] {dags_utils.py:93} INFO - [SUCCESS] Inserted 10 rows into raw.events
[2025-09-10T14:18:55.890+0000] {base.py:1052} INFO - Stopping heartbeat thread
[2025-09-10T14:18:55.890+0000] {base.py:891} INFO - Leaving consumer group (***_batch_consumer).
[2025-09-10T14:18:55.907+0000] {base.py:907} INFO - LeaveGroup request for group ***_batch_consumer returned successfully
[2025-09-10T14:18:55.907+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. 
[2025-09-10T14:18:55.908+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>
[2025-09-10T14:18:55.909+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=coordinator-1 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Closing connection. 
[2025-09-10T14:18:55.910+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-09-10T14:18:55.926+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=kafka_to_postgres_batch, task_id=consume_and_save_batch, execution_date=20250910T134809, start_date=20250910T141821, end_date=20250910T141855
[2025-09-10T14:18:57.005+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-10T14:18:57.039+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
