[2025-09-15T19:24:51.257+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T19:24:51.382+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-15T18:52:37.260987+00:00 [queued]>
[2025-09-15T19:24:51.396+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-15T18:52:37.260987+00:00 [queued]>
[2025-09-15T19:24:51.397+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 4
[2025-09-15T19:24:51.425+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonSensor): wait_for_kafka> on 2025-09-15 18:52:37.260987+00:00
[2025-09-15T19:24:51.439+0000] {standard_task_runner.py:57} INFO - Started process 598 to run task
[2025-09-15T19:24:51.449+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_postgres_batch', 'wait_for_kafka', 'scheduled__2025-09-15T18:52:37.260987+00:00', '--job-id', '418', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpk08c8kzo']
[2025-09-15T19:24:51.462+0000] {standard_task_runner.py:85} INFO - Job 418: Subtask wait_for_kafka
[2025-09-15T19:24:51.505+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T19:24:51.564+0000] {task_command.py:410} INFO - Running <TaskInstance: kafka_to_postgres_batch.wait_for_kafka scheduled__2025-09-15T18:52:37.260987+00:00 [running]> on host 4ba3580a27fc
[2025-09-15T19:24:51.592+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T19:24:51.753+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_postgres_batch' AIRFLOW_CTX_TASK_ID='wait_for_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T18:52:37.260987+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T18:52:37.260987+00:00'
[2025-09-15T19:24:51.755+0000] {python.py:72} INFO - Poking callable: <function check_kafka_message at 0x7fb12c3e7a70>
[2025-09-15T19:24:51.760+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.23.0.4', 29092)]>: connecting to kafka:29092 [('172.23.0.4', 29092) IPv4]
[2025-09-15T19:24:51.774+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.4', 29092)]>: Broker version identified as 2.6
[2025-09-15T19:24:51.775+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.23.0.4', 29092)]>: Connection complete.
[2025-09-15T19:24:51.779+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('user_events',)
[2025-09-15T19:24:51.784+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('user_events', 0)]
[2025-09-15T19:24:51.786+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.23.0.4', 29092)]>: connecting to kafka:29092 [('172.23.0.4', 29092) IPv4]
[2025-09-15T19:24:51.788+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.23.0.4', 29092)]>: Connection complete.
[2025-09-15T19:24:51.788+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.23.0.4', 29092)]>: Closing connection. 
[2025-09-15T19:24:51.862+0000] {fetcher.py:418} INFO - Resetting offset for partition ('user_events', 0) to offset 0.
[2025-09-15T19:24:52.182+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.23.0.4', 29092)]>: Closing connection. 
[2025-09-15T19:24:52.184+0000] {base.py:255} INFO - Success criteria met. Exiting.
[2025-09-15T19:24:52.241+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=kafka_to_postgres_batch, task_id=wait_for_kafka, execution_date=20250915T185237, start_date=20250915T192451, end_date=20250915T192452
[2025-09-15T19:24:52.245+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-09-15T19:24:52.952+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-15T19:24:53.078+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
