[2025-09-03T15:48:42.066+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.create_indexes manual__2025-09-03T15:37:51.116927+00:00 [queued]>
[2025-09-03T15:48:42.101+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.create_indexes manual__2025-09-03T15:37:51.116927+00:00 [queued]>
[2025-09-03T15:48:42.102+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-09-03T15:48:42.147+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_indexes> on 2025-09-03 15:37:51.116927+00:00
[2025-09-03T15:48:42.171+0000] {standard_task_runner.py:57} INFO - Started process 1089 to run task
[2025-09-03T15:48:42.174+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_postgres_batch', 'create_indexes', 'manual__2025-09-03T15:37:51.116927+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp8nxn72ln']
[2025-09-03T15:48:42.179+0000] {standard_task_runner.py:85} INFO - Job 120: Subtask create_indexes
[2025-09-03T15:48:42.243+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T15:48:42.409+0000] {task_command.py:410} INFO - Running <TaskInstance: kafka_to_postgres_batch.create_indexes manual__2025-09-03T15:37:51.116927+00:00 [running]> on host 5646b9718ecc
[2025-09-03T15:48:42.629+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_postgres_batch' AIRFLOW_CTX_TASK_ID='create_indexes' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T15:37:51.116927+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T15:37:51.116927+00:00'
[2025-09-03T15:48:42.631+0000] {sql.py:265} INFO - Executing: 
        CREATE INDEX IF NOT EXISTS idx_raw_events_user_id ON raw.events(user_id);
        CREATE INDEX IF NOT EXISTS idx_raw_events_timestamp ON raw.events(timestamp);
        CREATE INDEX IF NOT EXISTS idx_raw_events_event_type ON raw.events(event_type);
        
[2025-09-03T15:48:42.660+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-03T15:48:42.867+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-03T15:48:42.885+0000] {sql.py:375} INFO - Running statement: 
        CREATE INDEX IF NOT EXISTS idx_raw_events_user_id ON raw.events(user_id);
        CREATE INDEX IF NOT EXISTS idx_raw_events_timestamp ON raw.events(timestamp);
        CREATE INDEX IF NOT EXISTS idx_raw_events_event_type ON raw.events(event_type);
        , parameters: None
[2025-09-03T15:48:42.925+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=kafka_to_postgres_batch, task_id=create_indexes, execution_date=20250903T153751, start_date=20250903T154842, end_date=20250903T154842
[2025-09-03T15:48:43.004+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-03T15:48:43.065+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
