[2025-09-15T22:13:02.101+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T22:13:02.221+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-15T22:11:55.557503+00:00 [queued]>
[2025-09-15T22:13:02.235+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-15T22:11:55.557503+00:00 [queued]>
[2025-09-15T22:13:02.236+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-09-15T22:13:02.262+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): produce_entities_and_events> on 2025-09-15 22:11:55.557503+00:00
[2025-09-15T22:13:02.273+0000] {standard_task_runner.py:57} INFO - Started process 1612 to run task
[2025-09-15T22:13:02.274+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'generate_events_minutely', 'produce_entities_and_events', 'scheduled__2025-09-15T22:11:55.557503+00:00', '--job-id', '491', '--raw', '--subdir', 'DAGS_FOLDER/generator_dag.py', '--cfg-path', '/tmp/tmpil77p37_']
[2025-09-15T22:13:02.281+0000] {standard_task_runner.py:85} INFO - Job 491: Subtask produce_entities_and_events
[2025-09-15T22:13:02.399+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T22:13:02.495+0000] {task_command.py:410} INFO - Running <TaskInstance: generate_events_minutely.produce_entities_and_events scheduled__2025-09-15T22:11:55.557503+00:00 [running]> on host 71d7292233fc
[2025-09-15T22:13:02.561+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-15T22:13:04.943+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='generate_events_minutely' AIRFLOW_CTX_TASK_ID='produce_entities_and_events' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T22:11:55.557503+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T22:11:55.557503+00:00'
[2025-09-15T22:13:04.957+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.23.0.2', 29092)]>: connecting to kafka:29092 [('172.23.0.2', 29092) IPv4]
[2025-09-15T22:13:04.985+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.23.0.2', 29092)]>: Broker version identified as 2.6
[2025-09-15T22:13:04.986+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.23.0.2', 29092)]>: Connection complete.
[2025-09-15T22:13:07.498+0000] {conn.py:397} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connecting> [IPv4 ('172.23.0.2', 29092)]>: connecting to kafka:29092 [('172.23.0.2', 29092) IPv4]
[2025-09-15T22:13:07.499+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.23.0.2', 29092)]>: Connection complete.
[2025-09-15T22:13:07.500+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.23.0.2', 29092)]>: Closing connection. 
[2025-09-15T22:13:12.151+0000] {kafka.py:629} INFO - <KafkaProducer client_id=kafka-python-producer-1 transactional_id=None>: Closing the Kafka producer with 9223372036.0 secs timeout.
[2025-09-15T22:13:12.153+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=kafka:29092 <connected> [IPv4 ('172.23.0.2', 29092)]>: Closing connection. 
[2025-09-15T22:13:12.154+0000] {generator_dag.py:34} INFO - Produced 5 messages to Kafka
[2025-09-15T22:13:12.155+0000] {python.py:183} INFO - Done. Returned value was: 5
[2025-09-15T22:13:12.227+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=generate_events_minutely, task_id=produce_entities_and_events, execution_date=20250915T221155, start_date=20250915T221302, end_date=20250915T221312
[2025-09-15T22:13:12.230+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-09-15T22:13:12.706+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-15T22:13:12.758+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
