[2025-09-03T16:39:06.104+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.create_events_table manual__2025-09-03T16:38:40.717967+00:00 [queued]>
[2025-09-03T16:39:06.126+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_postgres_batch.create_events_table manual__2025-09-03T16:38:40.717967+00:00 [queued]>
[2025-09-03T16:39:06.127+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2025-09-03T16:39:06.199+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_events_table> on 2025-09-03 16:38:40.717967+00:00
[2025-09-03T16:39:06.338+0000] {standard_task_runner.py:57} INFO - Started process 198 to run task
[2025-09-03T16:39:06.347+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_postgres_batch', 'create_events_table', 'manual__2025-09-03T16:38:40.717967+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpd1x5zdcl']
[2025-09-03T16:39:06.352+0000] {standard_task_runner.py:85} INFO - Job 191: Subtask create_events_table
[2025-09-03T16:39:06.454+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-03T16:39:06.536+0000] {task_command.py:410} INFO - Running <TaskInstance: kafka_to_postgres_batch.create_events_table manual__2025-09-03T16:38:40.717967+00:00 [running]> on host 5646b9718ecc
[2025-09-03T16:39:06.801+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_postgres_batch' AIRFLOW_CTX_TASK_ID='create_events_table' AIRFLOW_CTX_EXECUTION_DATE='2025-09-03T16:38:40.717967+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-03T16:38:40.717967+00:00'
[2025-09-03T16:39:06.802+0000] {sql.py:265} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS raw.events (
            id SERIAL PRIMARY KEY,
            user_id INT,
            event_type TEXT,
            city TEXT,
            country TEXT,
            lat DOUBLE PRECISION,
            lon DOUBLE PRECISION,
            cost_usd NUMERIC(10,2),
            cost_eur NUMERIC(10,2),
            cost_rub NUMERIC(10,2),
            weather_temp NUMERIC(5,2),
            weather_desc TEXT,
            timestamp TIMESTAMPTZ DEFAULT NOW()
        );
        
[2025-09-03T16:39:06.821+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-03T16:39:07.188+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-09-03T16:39:07.388+0000] {sql.py:375} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS raw.events (
            id SERIAL PRIMARY KEY,
            user_id INT,
            event_type TEXT,
            city TEXT,
            country TEXT,
            lat DOUBLE PRECISION,
            lon DOUBLE PRECISION,
            cost_usd NUMERIC(10,2),
            cost_eur NUMERIC(10,2),
            cost_rub NUMERIC(10,2),
            weather_temp NUMERIC(5,2),
            weather_desc TEXT,
            timestamp TIMESTAMPTZ DEFAULT NOW()
        );
        , parameters: None
[2025-09-03T16:39:07.455+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=kafka_to_postgres_batch, task_id=create_events_table, execution_date=20250903T163840, start_date=20250903T163906, end_date=20250903T163907
[2025-09-03T16:39:07.527+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-09-03T16:39:07.578+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
